[package]
name = "simple-calculator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-rational = "0.4.1"
regex = "1.7.0" # possibly replace with proc-macro-regex to improve performance